plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/illaviktorovna/where-party/miniapp"
publishOrigin = "config"
base = "/Users/illaviktorovna/where-party/miniapp"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]